import hashlib
import logging
import os
import re
import smtplib
import textwrap
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import parseaddr
from typing import Any, Dict, Iterable

from google.adk.agents.callback_context import CallbackContext
from google.adk.tools import BaseTool
from google.cloud import logging as cloud_logging

logger = logging.getLogger(__name__)


def validate_email(email: str) -> str:
    """Validate and sanitize an email address.

    Args:
        email: Raw email input from user.

    Returns:
        A sanitized and validated email address.

    Raises:
        ValueError: If the email is missing or does not match a basic pattern.
    """
    email = email.replace("\n", "").replace("\r", "")

    name, addr = parseaddr(email)
    if not addr or "@" not in addr:
        raise ValueError("Invalid email format")

    if not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", addr):
        raise ValueError("Invalid email format")

    return addr


def before_tool(
    tool: BaseTool,
    args: Dict[str, Any],
    tool_context: CallbackContext,
) -> None:
    """Attach conversation history to tool args before execution.

    Args:
        tool: The tool about to run.
        args: Arguments that will be passed to the tool.
        tool_context: Callback context providing session data.
    """
    args["conversation_history"] = build_conversation_history(tool_context)


def build_conversation_history(tool_context: CallbackContext) -> str:
    """Format session events into a plain-text transcript.

    Args:
        tool_context: Callback context containing session events.

    Returns:
        A newline-delimited string of USER/ASSISTANT dialogue.
    """
    lines: list[str] = []
    role_map = {"user": "USER", "dgen_agent": "ASSISTANT"}

    for event in getattr(tool_context.session, "events", []) or []:
        author = getattr(event, "author", None)
        role = role_map.get(author)
        if not role:
            continue

        content = getattr(event, "content", None)
        parts = getattr(content, "parts", None) or []
        texts = _extract_texts(parts)
        joined = " ".join(texts)
        if not joined:
            continue

        lines.append(f"{role}: {joined}")

    return "\n".join(lines)


def _extract_texts(parts: Iterable[Any]) -> list[str]:
    """Collect non-empty text parts from agent event parts.

    Args:
        parts: Iterable of event parts with optional text attribute.

    Returns:
        List of stripped text entries.
    """
    return [
        part.text.strip()
        for part in parts
        if getattr(part, "text", None) and str(part.text).strip()
    ]


def _mask_email(email: str) -> str:
    """Mask email for logs with consistent format.

    Args:
        email: The email address to mask.

    Returns:
        A masked email string that hides the local part.
    """
    if "@" in email and len(email) > 3:
        local, domain = email.split("@", 1)
        hashed = hashlib.sha256(local.encode()).hexdigest()[:6]
        return f"{local[0]}***{hashed}@{domain}"
    # Fallback: full hash
    return hashlib.sha256(email.encode()).hexdigest()[:16]


def _build_email_content(
    user_email: str, issue_summary: str, conversation_history: str
) -> tuple[str, str]:
    """Build the email subject and body for support escalation.

    Args:
        user_email: Validated user email address.
        issue_summary: Summary of the user's issue.
        conversation_history: Transcript of the conversation.

    Returns:
        Tuple of subject and body strings.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    subject = f"[DGEN Support] Issue from {user_email}"
    body = textwrap.dedent(
        f"""
DGEN SUPPORT TICKET

Timestamp: {timestamp}
User Email: {user_email}

====================
ISSUE SUMMARY
====================
{issue_summary}

====================
CONVERSATION HISTORY
====================
{conversation_history}

-- Generated by DGEN AI Assistant
"""
    ).strip()
    return subject, body


def send_escalation_email(
    user_email: str,
    issue_summary: str,
    conversation_history: str,
) -> str:
    """Escalate unresolved user issues to the support team via SMTP.

    Args:
        user_email: User email to contact.
        issue_summary: Short description of the issue.
        conversation_history: Conversation transcript.

    Returns:
        A confirmation or error message for LLM as tool output.
    """
    cloud_logging.Client().setup_logging()

    sanitized_email = validate_email(user_email)
    masked_email = _mask_email(sanitized_email)
    logger.info(
        msg={
            "event": "escalation_email_invoked",
            "payload": {"user_email": masked_email},
        }
    )

    subject, body = _build_email_content(
        user_email=sanitized_email,
        issue_summary=issue_summary,
        conversation_history=conversation_history,
    )

    EMAIL_FROM = "no-reply@dgentech.io"
    EMAIL_TO = "support@dgentech.io"

    SMTP_HOST = os.environ["SMTP_HOST"]
    SMTP_PORT = int(os.environ["SMTP_PORT"])
    SMTP_USER = os.environ["SMTP_USER"]
    SMTP_PASSWORD = os.environ["SMTP_PASSWORD"]

    msg = MIMEMultipart()
    msg["From"] = EMAIL_FROM
    msg["To"] = EMAIL_TO
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())

        logger.info(
            msg={
                "event": "escalation_email_sent",
                "payload": {"user_email": masked_email},
            }
        )
        return (
            f"Your issue has been successfully sent to our support team. "
            f"They will respond to you at **{user_email}** shortly."
        )

    except Exception as e:
        error_type = e.__class__.__name__
        logger.error(
            msg={
                "event": "escalation_email_failed",
                "payload": {
                    "user_email": masked_email,
                    "error_type": error_type,  # avoid logging sensitive error messages/creds
                },
            },
            exc_info=True,
        )

        return (
            "We couldn't submit your request to support at the moment. "
            "Please try again in a few minutes or contact us on our Telegram channel."
        )
