import os
import smtplib
import textwrap
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, Iterable

from google.adk.agents.callback_context import CallbackContext
from google.adk.tools import BaseTool


def before_tool(
    tool: BaseTool,
    args: Dict[str, Any],
    tool_context: CallbackContext,
) -> None:
    args["conversation_history"] = build_conversation_history(tool_context)


def build_conversation_history(tool_context: CallbackContext) -> str:
    """Format session events into a plain-text dialogue transcript."""
    lines: list[str] = []
    role_map = {"user": "USER", "dgen_agent": "ASSISTANT"}

    for event in getattr(tool_context.session, "events", []) or []:
        author = getattr(event, "author", None)
        role = role_map.get(author)
        if not role:
            continue

        content = getattr(event, "content", None)
        parts = getattr(content, "parts", None) or []
        texts = _extract_texts(parts)
        joined = " ".join(texts)
        if not joined:
            continue

        lines.append(f"{role}: {joined}")

    return "\n".join(lines)


def _extract_texts(parts: Iterable[Any]) -> list[str]:
    return [
        part.text.strip()
        for part in parts
        if getattr(part, "text", None) and str(part.text).strip()
    ]


def send_escalation_email(
    user_email: str,
    issue_summary: str,
    conversation_history: str,
    # session_id: str | None = None,
) -> str:
    """
    Escalate unresolved user issues to the support team via SMTP.

    Required data:
    - user_email
    - issue_summary
    - conversation_history
    - session_id (optional)

    Returns a confirmation message for the user.
    """
    EMAIL_FROM = "no-reply@dgentech.io"
    EMAIL_TO = "support@dgentech.io"
    SMTP_HOST = os.environ["SMTP_HOST"]
    SMTP_PORT = os.environ["SMTP_PORT"]
    SMTP_USER = os.environ["SMTP_USER"]
    smtp_password = os.environ["SMTP_PASSWORD"]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    subject = f"[DGEN Support] Issue from {user_email}"

    body = textwrap.dedent(
        f"""
DGEN SUPPORT TICKET

Timestamp: {timestamp}
User Email: {user_email}

====================
ISSUE SUMMARY
====================
{issue_summary}

====================
CONVERSATION HISTORY
====================
{conversation_history}

-- Generated by DGEN AI Assistant
"""
    ).strip()

    msg = MIMEMultipart()
    msg["From"] = EMAIL_FROM
    msg["To"] = EMAIL_TO
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, smtp_password)
            server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())

        return (
            f"Your issue has been successfully sent to our support team. "
            f"They will respond to you at **{user_email}** shortly."
        )

    except Exception as e:
        print(f"SMTP Error: {e}")
        return (
            "I encountered a problem sending your request to support. "
            "Please try again later."
        )
