[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agent"
version = "1.0.0"
description = "Deploys a Google ADK agent on Vertex AI."
requires-python = "~=3.13.0"
dependencies = [
    "absl-py>=2.3.1",
    "google-adk[eval]>=1.12.0",
    "google-auth>=2.40.3",
    "google-cloud-aiplatform[agent_engines]>=1.101.0,!=1.92.0",
    "google-cloud-secret-manager",
    "google-genai>=1.5.0,<2.0.0",
    "google-cloud-logging>=3.12.0",
    "litellm>=1.80.0",
    "openinference-instrumentation-google-adk>=0.1.4",
    "pydantic>=2.10.6,<3.0.0",
]

[tool.uv]
default-groups = "all"
